### ISSUE TITLE
Undefined when RegExp

### ISSUE THREAD

**Issue by magbicaleman** [bramstein/funcy#7]
``` js
// matches /ok$/ regular expression
[/ok$/,function(){}]
```

Is this suppose to pass into the function? I'm getting an undefined when

``` js
[/ok$/, (v) => console.log(v)]
```

**Comment by alexghenderson** [comment]
I've encountered the same issue. I've created a PR #8 to resolve this issue.

**Comment by bramstein** [comment]
This is fixed now, thanks to @alexghenderson.
